In [72]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from helpers import *

# from test_utils import test

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


## Loading

### All variables Cleanup

In [63]:
### remettre "ID" pour csv 
label_list = ["MSCODE", "_HCVU651", "_RFHYPE5", "_RFCHOL", "_RACE", "_BMI5", "_EDUCAG", "_INCOMG", "_SMOKER3", "_DRNKWEK", "_FRUTSUM", "_VEGESUM", "PA1MIN_"]
label_ids = np.where(np.isin(labels, label_list))[0]
# list taken from website -1 is actually None 
exception_list = [-1,9,9,9,9,-1,9,9,9,99900,-1,-1,-1]

print(len(exception_list))

print(label_ids)
print(len(label_list))
print(len(label_ids))


13
[218 231 232 234 242 253 257 258 259 264 276 277 301]
13
13


In [97]:
### ajoute initialement les ids
#tab = [ids]

tab_r = []

label_arr = np.array(label_list)

for i, j in zip(label_list, exception_list):
    id_r = np.where(label_arr == i)[0][0]  # Find the index using NumPy
    var_r = y[:, label_ids[id]]
    tab_r.append(data_clean(var_r, j))


resulting_array = np.array(tab_r).T

print(resulting_array)
print(len(resulting_array))

[[ 30  30  30 ...  30  30  30]
 [ 60  60  60 ...  60  60  60]
 [100 100 100 ... 100 100 100]
 ...
 [ 82  82  82 ...  82  82  82]
 [ 82  82  82 ...  82  82  82]
 [  0   0   0 ...   0   0   0]]
109379


## Run de A a Z - Ridge Regression 

### Loading  data 

In [1]:
x_train, x_test, y_train, train_ids, test_ids = load_csv_data("dataset")


NameError: name 'load_csv_data' is not defined

### Output labels 

In [163]:
labels = np.genfromtxt("dataset/x_test.csv", delimiter=",", dtype = str, max_rows=1)
labels = np.delete(labels,0)

In [164]:
labels[0]

'_STATE'

### Cleaning

In [165]:
### add "ID" for csv file creation
label_list = ["MSCODE", "_HCVU651", "_RFHYPE5", "_RFCHOL", "_RACE", "_BMI5", "_EDUCAG", "_INCOMG", "_SMOKER3", "_DRNKWEK", "_FRUTSUM", "_VEGESUM", "PA1MIN_"]
label_ids = np.where(np.isin(labels, label_list))[0]

# list taken from website -1 is actually None 
exception_list = [-1,9,9,9,9,-1,9,9,9,99900,-1,-1,-1]

print(label_list)
print(label_ids)
print(len(label_list))
print(len(label_ids))
print(len(exception_list))

['MSCODE', '_HCVU651', '_RFHYPE5', '_RFCHOL', '_RACE', '_BMI5', '_EDUCAG', '_INCOMG', '_SMOKER3', '_DRNKWEK', '_FRUTSUM', '_VEGESUM', 'PA1MIN_']
[218 231 232 234 242 253 257 258 259 264 276 277 301]
13
13
13


In [185]:
x_train[:][218]


array([3.60000000e+01, 1.10000000e+01, 1.11620150e+07, 1.10000000e+01,
       1.60000000e+01, 2.01500000e+03, 1.10000000e+03, 2.01500858e+09,
       2.01500858e+09, 1.00000000e+00, 1.00000000e+00,            nan,
       1.00000000e+00, 2.00000000e+00,            nan, 1.00000000e+00,
       0.00000000e+00, 1.00000000e+00,            nan,            nan,
                  nan,            nan,            nan,            nan,
                  nan,            nan, 3.00000000e+00, 1.00000000e+01,
       8.80000000e+01, 3.00000000e+01, 1.00000000e+00, 1.00000000e+00,
       2.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 2.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 2.00000000e+00, 2.00000000e+00,
       1.00000000e+00, 6.50000000e+01, 2.00000000e+00, 3.00000000e+00,
       5.00000000e+00, 2.00000000e+00, 2.00000000e+00,            nan,
      

In [146]:
tab_train = []
label_arr = np.array(label_list)

for i, j in zip(label_list, exception_list):
    id = np.where(label_arr == i)[0][0] 
    var = x_train[:, label_ids[id]]
    print(label_ids[id])
    tab_train.append(data_clean(var, j))

cleaned_x_train = np.array(tab_train).T

print(cleaned_x_train)
print(len(cleaned_x_train))
print(len(cleaned_x_train[0]))

218
There are NaN values
231
232
234
242
253
There are NaN values
257
258
259
264
276
There are NaN values
277
301
There are NaN values
[[2.54225970e+00 1.00000000e+00 1.00000000e+00 ... 7.10000000e-01
  1.21000000e+00 2.00000000e+02]
 [5.00000000e+00 1.00000000e+00 2.00000000e+00 ... 1.36179859e+00
  1.94943283e+00 4.82813551e+02]
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 ... 2.03000000e+00
  2.86000000e+00 9.00000000e+01]
 ...
 [1.00000000e+00 1.00000000e+00 1.00000000e+00 ... 1.00000000e+00
  7.80000000e-01 1.20000000e+02]
 [5.00000000e+00 1.00000000e+00 1.00000000e+00 ... 7.00000000e-02
  3.60000000e-01 2.80000000e+01]
 [1.00000000e+00 1.00000000e+00 2.00000000e+00 ... 4.00000000e+00
  7.00000000e+00 0.00000000e+00]]
328135
13


### Training

#### Ridge regression

In [59]:
lambda_ = 0.0001
degree = 7
## tx is cleaned data 
poly = build_poly(resulting_array_t,degree)
w , loss = ridge_regression(yb,poly,lambda_)

In [60]:
print(w)
print(loss)

[ 1.56537189e-02  1.34991226e-02  1.54709421e-02  1.54765743e-02
  1.54760025e-02 -7.72468004e-02 -7.58913295e-03  1.30106606e-02
  9.76146968e-03  1.33910074e-02 -7.82318362e-06  7.32856501e-04
 -3.49111254e-03  5.15987981e-06  9.79173925e-03  1.51053884e-02
  1.51222850e-02  1.51205697e-02 -4.87075070e-02  2.86958669e-04
  8.60427231e-03  1.94257734e-03  9.59241756e-03  1.40082321e-10
  1.88029531e-04  1.99166118e-04 -6.57706662e-11  4.06470659e-03
  1.43742811e-02  1.44137061e-02  1.44097038e-02  6.92860312e-02
 -4.42143992e-06  2.11881698e-03 -5.25788581e-03  3.92243482e-03
 -8.10571012e-12 -3.82436291e-06 -2.53239109e-06  1.67363363e-12
 -2.91463574e-03  1.29120663e-02  1.29965487e-02  1.29879726e-02
 -2.82315284e-02  2.30405430e-08 -5.11757412e-03 -5.53092270e-03
 -2.64908212e-03 -4.10933693e-12  1.80794218e-08  8.15377990e-09
 -2.47779878e-12 -6.39151114e-03  9.98763718e-03  1.01622358e-02
  1.01445083e-02  5.39570779e-03 -1.55133371e-12 -7.37665283e-03
  4.83953004e-03 -5.53957

#### Testing

In [68]:
poly_test = build_poly(resulting_array,degree)
                                 

#### Prediction

In [69]:
yp = predict_labels(w,poly_test)

In [70]:
print(yp)

[ 1. -1.  1. ...  1.  1.  1.]


#### CSV Submission

In [74]:
create_csv_submission(ids,yp,"ridge_1e-4_7_output.csv")